using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FinanceFunction.Models
{
		public class UserCredential
		{
				// Primary Key
				public Guid Id { get; set; }

				// Unique Credential ID generated by the Authenticator/Browser
				// This is a byte array stored as a string or byte array in the DB
				public string CredentialId { get; set; }

				// Public Key associated with this credential
				// This is a byte array stored as a string or byte array in the DB (e.g., Base64URL)
				public string PublicKey { get; set; }

				// Used to prevent replay attacks and must be incremented on every successful assertion/login
				public uint SignCount { get; set; }

				// Link to your ApplicationUser model
				public Guid UserId { get; set; }

				[ForeignKey("UserId")]
				public User User { get; set; }

				// Optional: Device nickname, date created, etc.
				public string DeviceName { get; set; }
				public DateTimeOffset CreatedDate { get; set; }
				public string PartitionKey { get; set; } = "default";
		}
}
