name: Build and Push Docker

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

  
jobs:

  build:

    runs-on: ubuntu-latest

    environment: GITHUB_TOKEN
    steps:
    - uses: actions/checkout@v4

    - run: echo "VERSION_NUM=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        
    - name: Build the Docker image
      run: docker build FinanceProject/. --file FinanceProject/Dockerfile --tag ghcr.io/adolf94/financeapp:${{env.VERSION_NUM}} 
      
    - uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{secrets.TOKEN_USER}}
        password: ${{secrets.TOKEN_ACTION}}


    - name: Push the docker image to ghcr.io
      run: docker push ghcr.io/adolf94/financeapp:${{env.VERSION_NUM}}
      
      
